/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author strange
 */
public class SignupClient extends javax.swing.JFrame {

    /**
     * Creates new form SignupClient
     */
    public SignupClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderRegClient = new javax.swing.JPanel();
        TitleRegClient = new javax.swing.JLabel();
        PanelRegClient = new javax.swing.JPanel();
        NameRegClient = new javax.swing.JLabel();
        LastnPaClient = new javax.swing.JLabel();
        LastMaClient = new javax.swing.JLabel();
        PhoneClient = new javax.swing.JLabel();
        EmailClient = new javax.swing.JLabel();
        IdClient = new javax.swing.JLabel();
        CityClient = new javax.swing.JLabel();
        NameTxtFieldClient = new javax.swing.JTextField();
        LastnPaTxtFieldClient = new javax.swing.JTextField();
        LastnMaTxtFieldClient = new javax.swing.JTextField();
        PhoneTxtFieldClient = new javax.swing.JTextField();
        EmailTxtFieldClient = new javax.swing.JTextField();
        IdclientTxtFieldClient = new javax.swing.JTextField();
        CityTxtFieldClient = new javax.swing.JTextField();
        RegClient = new javax.swing.JButton();
        ShowClient = new javax.swing.JButton();
        UpdateClient = new javax.swing.JButton();
        DeleteClient = new javax.swing.JButton();
        bgColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleRegClient.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TitleRegClient.setText("REGISTRO DE CLIENTES");

        javax.swing.GroupLayout HeaderRegClientLayout = new javax.swing.GroupLayout(HeaderRegClient);
        HeaderRegClient.setLayout(HeaderRegClientLayout);
        HeaderRegClientLayout.setHorizontalGroup(
            HeaderRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleRegClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderRegClientLayout.setVerticalGroup(
            HeaderRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleRegClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(HeaderRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 40));

        NameRegClient.setText("Nombre:");

        LastnPaClient.setText("Apellido paterno:");

        LastMaClient.setText("Apellido materno:");

        PhoneClient.setText("Celular:");

        EmailClient.setText("Email:");

        IdClient.setText("Id cliente:");

        CityClient.setText("Ciudad:");

        RegClient.setText("Registrar");

        ShowClient.setText("Mostrar");

        UpdateClient.setText("Actualizar");

        DeleteClient.setText("Eliminar");

        javax.swing.GroupLayout PanelRegClientLayout = new javax.swing.GroupLayout(PanelRegClient);
        PanelRegClient.setLayout(PanelRegClientLayout);
        PanelRegClientLayout.setHorizontalGroup(
            PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameRegClient)
                    .addComponent(LastnPaClient)
                    .addComponent(LastMaClient)
                    .addComponent(PhoneClient)
                    .addComponent(EmailClient)
                    .addComponent(IdClient)
                    .addComponent(CityClient))
                .addGap(39, 39, 39)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameTxtFieldClient)
                    .addComponent(LastnPaTxtFieldClient)
                    .addComponent(LastnMaTxtFieldClient)
                    .addComponent(PhoneTxtFieldClient)
                    .addComponent(EmailTxtFieldClient)
                    .addComponent(IdclientTxtFieldClient)
                    .addComponent(CityTxtFieldClient, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdateClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShowClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PanelRegClientLayout.setVerticalGroup(
            PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameRegClient)
                    .addComponent(NameTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegClient))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnPaClient)
                    .addComponent(LastnPaTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowClient))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastMaClient)
                    .addComponent(LastnMaTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateClient))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneClient)
                    .addComponent(PhoneTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteClient))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailClient)
                    .addComponent(EmailTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdClient)
                    .addComponent(IdclientTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityClient)
                    .addComponent(CityTxtFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(PanelRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 450, 280));

        bgColor.setBackground(new java.awt.Color(255, 255, 255));
        bgColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/white-background-2.jpg"))); // NOI18N
        getContentPane().add(bgColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityClient;
    private javax.swing.JTextField CityTxtFieldClient;
    private javax.swing.JButton DeleteClient;
    private javax.swing.JLabel EmailClient;
    private javax.swing.JTextField EmailTxtFieldClient;
    private javax.swing.JPanel HeaderRegClient;
    private javax.swing.JLabel IdClient;
    private javax.swing.JTextField IdclientTxtFieldClient;
    private javax.swing.JLabel LastMaClient;
    private javax.swing.JTextField LastnMaTxtFieldClient;
    private javax.swing.JLabel LastnPaClient;
    private javax.swing.JTextField LastnPaTxtFieldClient;
    private javax.swing.JLabel NameRegClient;
    private javax.swing.JTextField NameTxtFieldClient;
    private javax.swing.JPanel PanelRegClient;
    private javax.swing.JLabel PhoneClient;
    private javax.swing.JTextField PhoneTxtFieldClient;
    private javax.swing.JButton RegClient;
    private javax.swing.JButton ShowClient;
    private javax.swing.JLabel TitleRegClient;
    private javax.swing.JButton UpdateClient;
    private javax.swing.JLabel bgColor;
    // End of variables declaration//GEN-END:variables
}
