/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author strange
 */
public class SignupEmple extends javax.swing.JFrame {

    /**
     * Creates new form SignupEmple
     */
    public SignupEmple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderRegEmpl = new javax.swing.JPanel();
        TitleRegEmpl = new javax.swing.JLabel();
        PanelRegEmpl = new javax.swing.JPanel();
        NameRegEmpl = new javax.swing.JLabel();
        LastnPatEmpl = new javax.swing.JLabel();
        LastnMaEmpl = new javax.swing.JLabel();
        PhoneEmpl = new javax.swing.JLabel();
        EmailEmpl = new javax.swing.JLabel();
        UserEmpl = new javax.swing.JLabel();
        PassEmpl = new javax.swing.JLabel();
        NameTxtFieldEmpl = new javax.swing.JTextField();
        LastnPaTxtFieldEmpl = new javax.swing.JTextField();
        LastnMaTxtFieldEmpl = new javax.swing.JTextField();
        PhoneTxtFieldEmpl = new javax.swing.JTextField();
        EmailTxtFieldEmpl = new javax.swing.JTextField();
        UserTxtFieldEmpl = new javax.swing.JTextField();
        PassTxtFieldEmpl = new javax.swing.JTextField();
        RegBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleRegEmpl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        TitleRegEmpl.setText("REGISTRO DE EMPLEADOS");

        javax.swing.GroupLayout HeaderRegEmplLayout = new javax.swing.GroupLayout(HeaderRegEmpl);
        HeaderRegEmpl.setLayout(HeaderRegEmplLayout);
        HeaderRegEmplLayout.setHorizontalGroup(
            HeaderRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderRegEmplLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(TitleRegEmpl)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        HeaderRegEmplLayout.setVerticalGroup(
            HeaderRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderRegEmplLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(TitleRegEmpl)
                .addContainerGap())
        );

        getContentPane().add(HeaderRegEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 40));

        NameRegEmpl.setText("Nombre:");

        LastnPatEmpl.setText("Apellido paterno:");

        LastnMaEmpl.setText("Apellido materno:");

        PhoneEmpl.setText("Celular:");

        EmailEmpl.setText("Email:");

        UserEmpl.setText("Usuario:");

        PassEmpl.setText("Contraseña:");

        RegBtn.setText("Registrar");

        javax.swing.GroupLayout PanelRegEmplLayout = new javax.swing.GroupLayout(PanelRegEmpl);
        PanelRegEmpl.setLayout(PanelRegEmplLayout);
        PanelRegEmplLayout.setHorizontalGroup(
            PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegEmplLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PassEmpl)
                    .addGroup(PanelRegEmplLayout.createSequentialGroup()
                        .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastnPatEmpl)
                            .addComponent(NameRegEmpl))
                        .addGap(37, 37, 37)
                        .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameTxtFieldEmpl)
                            .addComponent(LastnPaTxtFieldEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                    .addGroup(PanelRegEmplLayout.createSequentialGroup()
                        .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastnMaEmpl)
                            .addComponent(PhoneEmpl)
                            .addComponent(EmailEmpl)
                            .addComponent(UserEmpl))
                        .addGap(35, 35, 35)
                        .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastnMaTxtFieldEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(PhoneTxtFieldEmpl)
                            .addComponent(EmailTxtFieldEmpl)
                            .addComponent(UserTxtFieldEmpl)
                            .addComponent(PassTxtFieldEmpl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(RegBtn)
                .addContainerGap())
        );
        PanelRegEmplLayout.setVerticalGroup(
            PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegEmplLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameRegEmpl)
                    .addComponent(NameTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegBtn))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnPatEmpl)
                    .addComponent(LastnPaTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnMaEmpl)
                    .addComponent(LastnMaTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneEmpl)
                    .addComponent(PhoneTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailEmpl)
                    .addComponent(EmailTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEmpl)
                    .addComponent(UserTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassEmpl)
                    .addComponent(PassTxtFieldEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelRegEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupEmple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupEmple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailEmpl;
    private javax.swing.JTextField EmailTxtFieldEmpl;
    private javax.swing.JPanel HeaderRegEmpl;
    private javax.swing.JLabel LastnMaEmpl;
    private javax.swing.JTextField LastnMaTxtFieldEmpl;
    private javax.swing.JTextField LastnPaTxtFieldEmpl;
    private javax.swing.JLabel LastnPatEmpl;
    private javax.swing.JLabel NameRegEmpl;
    private javax.swing.JTextField NameTxtFieldEmpl;
    private javax.swing.JPanel PanelRegEmpl;
    private javax.swing.JLabel PassEmpl;
    private javax.swing.JTextField PassTxtFieldEmpl;
    private javax.swing.JLabel PhoneEmpl;
    private javax.swing.JTextField PhoneTxtFieldEmpl;
    private javax.swing.JButton RegBtn;
    private javax.swing.JLabel TitleRegEmpl;
    private javax.swing.JLabel UserEmpl;
    private javax.swing.JTextField UserTxtFieldEmpl;
    // End of variables declaration//GEN-END:variables
}
