/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

/**
 *
 * @author strange
 */
public class SignupClient extends javax.swing.JFrame {

    /**
     * Creates new form SignupClient
     */
    public SignupClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegClient = new javax.swing.JPanel();
        NameRegClient = new javax.swing.JLabel();
        LastnPaClient = new javax.swing.JLabel();
        LastMaClient = new javax.swing.JLabel();
        PhoneClient = new javax.swing.JLabel();
        EmailClient = new javax.swing.JLabel();
        IdClient = new javax.swing.JLabel();
        CityClient = new javax.swing.JLabel();
        HeaderRegClient = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameRegClient.setText("Nombre:");

        LastnPaClient.setText("Apellido paterno:");

        LastMaClient.setText("Apellido materno:");

        PhoneClient.setText("Celular:");

        EmailClient.setText("Email:");

        IdClient.setText("Id cliente:");

        CityClient.setText("Ciudad:");

        javax.swing.GroupLayout PanelRegClientLayout = new javax.swing.GroupLayout(PanelRegClient);
        PanelRegClient.setLayout(PanelRegClientLayout);
        PanelRegClientLayout.setHorizontalGroup(
            PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameRegClient)
                    .addComponent(LastnPaClient)
                    .addComponent(LastMaClient)
                    .addComponent(PhoneClient)
                    .addComponent(EmailClient)
                    .addComponent(IdClient)
                    .addComponent(CityClient))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        PanelRegClientLayout.setVerticalGroup(
            PanelRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameRegClient)
                .addGap(18, 18, 18)
                .addComponent(LastnPaClient)
                .addGap(18, 18, 18)
                .addComponent(LastMaClient)
                .addGap(18, 18, 18)
                .addComponent(PhoneClient)
                .addGap(18, 18, 18)
                .addComponent(EmailClient)
                .addGap(18, 18, 18)
                .addComponent(IdClient)
                .addGap(18, 18, 18)
                .addComponent(CityClient)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(PanelRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, -1));

        javax.swing.GroupLayout HeaderRegClientLayout = new javax.swing.GroupLayout(HeaderRegClient);
        HeaderRegClient.setLayout(HeaderRegClientLayout);
        HeaderRegClientLayout.setHorizontalGroup(
            HeaderRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderRegClientLayout.setVerticalGroup(
            HeaderRegClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        getContentPane().add(HeaderRegClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 581, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityClient;
    private javax.swing.JLabel EmailClient;
    private javax.swing.JPanel HeaderRegClient;
    private javax.swing.JLabel IdClient;
    private javax.swing.JLabel LastMaClient;
    private javax.swing.JLabel LastnPaClient;
    private javax.swing.JLabel NameRegClient;
    private javax.swing.JPanel PanelRegClient;
    private javax.swing.JLabel PhoneClient;
    // End of variables declaration//GEN-END:variables
}
